### ISSUE TITLE
Upgrade to version 2.13.2 of exoplayer

### ISSUE THREAD

**Issue by lidord-wix** [DoubleSymmetry/react-native-track-player#1357]
**Is your feature request related to a problem? Please describe.**
The app crashes because I'm using `react-native-video` with version `2.13.2` of `exoplayer` 

**Describe the solution you'd like**
Upgrade the library to work with version `2.13.2` of `exoplayer` 

**Describe alternatives you've considered**
Using an alternative library based on the android audio player (instead of `exoplayer`)

**Additional context**
https://github.com/DoubleSymmetry/react-native-track-player/issues/1314
https://gist.github.com/Fairbrook/53127f8a05c020836a64f6c19b71f889

**Comment by bradleyflood** [comment]
Thanks @lidord-wix this makes sense. Could you create a pull request to resolve this?

**Comment by bradleyflood** [comment]
Tracking this also here https://github.com/DoubleSymmetry/react-native-track-player/issues/1364

**Comment by rizbud** [comment]
Thank you! It works for me

**Comment by SystemBlad** [comment]
Hi @lidord-wix. I had tried the patch everithing is working except this line of code:

`Player.MetadataComponent component = player.getMetadataComponent();`

in file:
android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java 

This error is shown, I think this getMetadataComponent method is not present in version 2.13.2.

```
2022-02-13 18:34:28.890 20562-20562/com.buildwitt E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.buildwitt, PID: 20562
    java.lang.NoSuchMethodError: No interface method getMetadataComponent()Lcom/google/android/exoplayer2/Player$MetadataComponent; in class Lcom/google/android/exoplayer2/Player; or its super classes (declaration of 'com.google.android.exoplayer2.Player' appears in /data/app/com.buildwitt-u7bMu5MKsrkTc3tAWxSZpQ==/base.apk)
        at com.guichaguri.trackplayer.service.player.ExoPlayback.<init>(ExoPlayback.java:57)
        at com.guichaguri.trackplayer.service.player.LocalPlayback.<init>(LocalPlayback.java:38)
        at com.guichaguri.trackplayer.service.MusicManager.createLocalPlayback(MusicManager.java:138)
        at com.guichaguri.trackplayer.service.MusicBinder.setupPlayer(MusicBinder.java:42)
        at com.guichaguri.trackplayer.module.MusicModule.lambda$setupPlayer$0$MusicModule(MusicModule.java:165)
        at com.guichaguri.trackplayer.module.-$$Lambda$MusicModule$fjHQ08dDKyrfXst5x4CJP27Uoh8.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

```

**Comment by MaxJadav** [comment]
@SystemBlad  Getting the same issue. Do you have a solution?
