### ISSUE TITLE
Build Failed with Android - "react-native-track-player:compileDebugKotlin FAILED"

### ISSUE THREAD

**Issue by I-am-Pritam-20** [doublesymmetry/react-native-track-player#2514]
### Description of the Bug
Android build failed while trying to build with react-native-track-player.

### Steps To Reproduce
Try using with latest react-native architecture, and other environment info provided below

### Code To Reproduce
Inside an existing react-native project
1. npm install --save react-native-track-player
2. npx react-native start 
(optional   npx react-native start --reset-cache)
3. npx react-native run-android

### Environment Info:
node: 20.19.9
npm : 11.0.0
java: 17.0.1
react: 19.1.0
react-native: 0.80.2

Android:
  hermesEnabled: true
  newArchEnabled: true

react-native-track-player: ^4.1.2

Real device

### Additional Info
react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/module/MusicModule.kt:548:51 Argument type mismatch: actual type is 'Bundle?', but 'Bundle' was expected.

react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/module/MusicModule.kt:588:17 Argument type mismatch: actual type is 'Bundle?', but 'Bundle' was expected. FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':react-native-track-player:compileDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error.

⚠️ **Seems like the issue has not been resolved yet**    @mpivchev  and  @jspizziri    If possible look into it.
* And also this ``` Bundle? ``` is working perfectly with  ``` react-native < 0.80.0 ```  ,  but not working with  ``` react-native >= 0.80.0 ``` , required ``` Bundle ```

**Comment by jspizziri** [comment]
Please don't waste peoples time by filing bugs before looking through past issues.

**Comment by I-am-Pritam-20** [comment]
The past issue has not been resolved yet that's why this error is showing up . And I have also checked for the same issue in the pool and you have mentioned in the discord that this fix won't be released until their is no confirmation.  You need more time or want me to show the error in the example ? Exactly whose confirmation is required ? Is not that person not aware of this issue ? Also you can reproduce the issue as per the environment info said above. If you want then I can also provide the other required package version (e.g. : ``` @react-native-community/cli ``` version to create the app). It's been a month this error is happening.

**Comment by jspizziri** [comment]
If you had actually done any amount of thorough investigation, you would've found that this issue is resolved in 5.0.0-alpha, and will not be backported to v4

**Comment by I-am-Pritam-20** [comment]
But the alpha version is breaking on iOS. Build getting successful but notification channel is not behaving as intended. Also controlling from notification, sometimes functions not working and sometimes UI state not changing.

Also the alpha version is some sort of malfunctioning (unintended behavior) in expo.

Therefore a stable version is required.
Hope you understand.

Or maybe I have to wait until the stable release version.

**Comment by jspizziri** [comment]
If you're having an issue with v5, then you should create  reproduction of your issue, document the exact steps to reproduce, and file an issue for that. We are moving forward with v5 and I'm not going to backport anything to v4.

**Comment by ChrisEdson** [comment]
@jspizziri friendly note: you sound quite combative and hostile. 

The issue listed isn't even strictly a duplicate, so you could understand why the OP posted this. 

As a collaborator on this project, let's stay kind, yeh?

**Comment by puckey** [comment]
@ChrisEdson always inspiring to see strong engagement from those leading by example in open-source development
