### ISSUE TITLE
Issues compiling for iOS off latest nightly build

### ISSUE THREAD

**Issue by msh1997** [doublesymmetry/react-native-track-player#1952]
**Describe the Bug**
When building the app for iOS, I'm getting a crash with the following error log

```
** BUILD FAILED **


The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'react-native-track-player' from project 'Pods')
	CompileSwift normal arm64 /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Models/Track.swift (in target 'react-native-track-player' from project 'Pods')
(2 failures)
```

From what I can see, the compile step is giving the following error
```
CompileSwift normal arm64 /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Models/Track.swift (in target 'react-native-track-player' from project 'Pods')
    cd /Users/michael/Workspace/react-native-track-player/example/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Models/Capabilities.swift /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Vendor/SwiftAudio/Classes/Utils/DispatchQueueType.swift /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Utils/EventEmitter.swift /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Utils/EventType.swift /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Models/MediaURL.swift /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Utils/Metadata.swift /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Models/PitchAlgorithms.swift /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Vendor/SwiftAudio/Classes/RepeatMode.swift /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/RNTrackPlayer.swift /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Models/SessionCategories.swift /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Models/State.swift -primary-file /Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Models/Track.swift -emit-module-path /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/Objects-normal/arm64/Track\~partial.swiftmodule -emit-module-doc-path /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/Objects-normal/arm64/Track\~partial.swiftdoc -emit-module-source-info-path /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/Objects-normal/arm64/Track\~partial.swiftsourceinfo -emit-dependencies-path /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/Objects-normal/arm64/Track.d -emit-reference-dependencies-path /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/Objects-normal/arm64/Track.swiftdeps -serialize-diagnostics-path /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/Objects-normal/arm64/Track.dia -target arm64-apple-ios11.0-simulator -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk -I /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Products/Debug-iphonesimulator/react-native-track-player -I /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Products/Debug-iphonesimulator/SwiftAudioEx -F /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Products/Debug-iphonesimulator/react-native-track-player -enable-testing -g -import-underlying-module -module-cache-path /Users/michael/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 4.2 -enforce-exclusivity\=checked -Onone -D DEBUG -D COCOAPODS -new-driver-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -serialize-debugging-options -Xcc -working-directory -Xcc /Users/michael/Workspace/react-native-track-player/example/ios/Pods -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -fmodule-map-file\=/Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Products/Debug-iphonesimulator/SwiftAudioEx/SwiftAudioEx.modulemap -Xcc -fmodule-map-file\=/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/React/React-Core.modulemap -Xcc -fmodule-map-file\=/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/yoga/Yoga.modulemap -Xcc -fmodule-map-file\=/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/react_native_track_player/react-native-track-player.modulemap -Xcc -I/Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/react-native-track-player-generated-files.hmap -Xcc -I/Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/react-native-track-player-own-target-headers.hmap -Xcc -I/Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/react-native-track-player-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/react-native-track-player-project-headers.hmap -Xcc -I/Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Products/Debug-iphonesimulator/react-native-track-player/include -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Private -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Private/react-native-track-player -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/DoubleConversion -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/RCT-Folly -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/React-Core -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/React-callinvoker -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/React-cxxreact -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/React-jsi -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/React-jsiexecutor -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/React-jsinspector -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/React-logger -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/React-perflogger -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/React-runtimeexecutor -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/Yoga -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/fmt -Xcc -I/Users/michael/Workspace/react-native-track-player/example/ios/Pods/Headers/Public/glog -Xcc -I/Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/DerivedSources-normal/arm64 -Xcc -I/Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/DerivedSources/arm64 -Xcc -I/Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG\=1 -Xcc -DDEBUG\=1 -Xcc -DCOCOAPODS\=1 -module-name react_native_track_player -target-sdk-version 15.2.0 -o /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-track-player.build/Objects-normal/arm64/Track.o -index-store-path /Users/michael/Library/Developer/Xcode/DerivedData/example-allmpbayxqlujodocqslqttsssgk/Index/DataStore -index-system-modules
/Users/michael/Workspace/react-native-track-player/ios/RNTrackPlayer/Models/Track.swift:137:25: error: cannot find 'AVURLAssetHTTPUserAgentKey' in scope
                options[AVURLAssetHTTPUserAgentKey] = userAgent
```

I encounter the exact same error when trying to build with the latest nightly build on my own app as well. It works on a previous version `3.2.0-d23c3fb990aaf9d6783881fabe21e059b62b0782`, but when I try to upgrade to one of the later versions where the SwiftAudioEx dependency was updated, the build started failing.

**Steps To Reproduce**
Going through each step in the Readme for the example app

**Code To Reproduce**
None

**Replicable on Example App?**
Yes, crashing when building the example app

**Environment Info:**
React Native info
```
info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1
    Memory: 23.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 25, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-29 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.4 is now available (your project is running on v0.68.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.4.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.68.5.
info To upgrade, run "react-native upgrade".
```
RNTP version: 3.2.0-bb749e5d286737681ba8907dfd287480eb1cec45 in my app, latest version off main for example app
OS: macOS Ventura 13.2.1

**How I can Help**
Is there a possible fix for these build issues? I tried cleaning my entire environment by wiping my npm/cocoapods cache, all build artefacts, etc.

**Comment by msh1997** [comment]
Digging further into it, it seems like reverting [this commit](https://github.com/doublesymmetry/react-native-track-player/pull/1907/commits/b882ddc13a359aa1364407f85fa8da51fec26538) solved the issue for me. No one from my team are experienced in swift but one of them tried the following change for line and it solved the build issue as well

before:
`options[AVURLAssetHTTPUserAgentKey] = userAgent`
after:
`options["AVURLAssetHTTPUserAgentKey"] = userAgent`

**Comment by mitchdowney** [comment]
For what it's worth, we are not running into this error in our app's iOS build with 3.2.0-bb749e5d286737681ba8907dfd287480eb1cec45

Here is our Podfile and package.json in case they are useful for someone:

https://github.com/podverse/podverse-rn/blob/594f275ebed07e6cdf8ac2bd13deb8f58f19926a/ios/Podfile

https://github.com/podverse/podverse-rn/blob/594f275ebed07e6cdf8ac2bd13deb8f58f19926a/package.json

**Comment by puckey** [comment]
The code related to this was introduced in https://github.com/doublesymmetry/react-native-track-player/pull/1816

@johnspurlock-skymethod perhaps you have an idea what could be causing this issue?

**Comment by johnspurlock-skymethod** [comment]
Hmm, not offhand, sorry.  Works in other apps like [PocketCasts](https://github.com/Automattic/pocket-casts-ios/pull/473/files) and Podverse as Mitch mentioned above.

Note that `AVURLAssetHTTPUserAgentKey` is [defined](https://developer.apple.com/documentation/avfoundation/avurlassethttpuseragentkey) in iOS16+ etc only, make sure your build server is configured correctly and your codebase has the appropriate `if #available` checks

**Comment by puckey** [comment]
@msh1997 what version of xcode are you encountering this issue on?

**Comment by msh1997** [comment]
Xcode 13.2.1

Full system info is
```
info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1
    Memory: 23.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 25, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-29 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.4 is now available (your project is running on v0.68.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.4.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.68.5.
info To upgrade, run "react-native upgrade".
```

**Comment by puckey** [comment]
Update xcode to 14.x

**Comment by waheedakhtar694** [comment]
@puckey I am using Xcode `14.2` and still getting this issue.

**Comment by rmilejcz** [comment]
on xcode 14.3 and also having this issue, none of the proposed solutions in any of the threads on this longstanding issue have addressed the problem
